# Generated by Django 4.2.6 on 2023-11-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_birth_date_alter_user_date_joined_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
