# Generated by Django 4.2.6 on 2023-11-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
