# Generated by Django 4.2.6 on 2023-12-03 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opt',
            fields=[
                ('passkey', models.CharField(max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
