# Generated by Django 4.2.6 on 2023-12-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_opt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opt',
            new_name='Otp',
        ),
    ]
