# Use an official Python runtime as a parent image
FROM python:3.10

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Install Django directly
RUN pip install Django==4.2.8

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

# Expose the port that Django will run on
EXPOSE 8000

# Run Django when the container launches
#CMD ["python", "manage.py", "runserver", "0.0.0.0:8080"]
