# Generated by Django 4.2.6 on 2024-01-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_cityfollowings'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
