# Generated by Django 4.2.6 on 2024-02-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default='ajab chize haghie!', max_length=500),
            preserve_default=False,
        ),
    ]
