# Generated by Django 5.0 on 2024-02-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_alter_comment_number_of_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='path',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='file_path',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='file_path',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
