# Generated by Django 5.0 on 2024-02-04 20:13

import experience.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0010_alter_post_image_alter_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=experience.models.upload_to_attractions),
        ),
    ]
