DONE = "Everything is OK!"
NECESSARY_FIELDS_REQUIRED = "Please provide necessary arguments!"
ATTRACTION_NOT_FOUND = "There is no attraction with this id!"
USER_NOT_FOUND = "User not found!"
CHAT_NOT_FOUND = "chat not found!"
ALREADY_EXISTS= "requested model already existed"
